//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
    public partial class Table
    {
        //public string DisplayTableCell
        //{
        //    //get
        //    //{
        //    //    if ()
        //    //    {
        //    //        this.
        //    //    }
        //    //    if (!string.IsNullOrEmpty(this.TextDate)) return this.TextDate;
        //    //    if (this.ActualDate != DateTime.MinValue) return this.ActualDate.ToString();
        //    //    return this.UpdateDate;


        //    //}
        //}
    }
}
